//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int SubjectID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Credit { get; set; }
        public string Hour { get; set; }
        public byte[] CourseID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
